---
- name: Configure hosts & deploy application
  hosts: all
  become: yes
  vars:
    mongo_bind_ip: 192.168.10.9
    db_host: 192.168.10.9
  tasks:
    - name: Change mongo config file
      become: true
      template:
        src:  templates/mongod.conf.j2 # <-- Путь до локального файла-шаблона
        dest: /etc/mongod.conf # <-- Путь на удаленном хосте
        mode: 0644
      tags: db-tag
      notify: restart mongod

    - name: Add unit file for Puma
      become: true
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: restart puma
      tags: app-tag

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
      tags: app-tag

    - name: enable puma
      become: yes
      systemd:
        name: puma
        enabled: yes
      tags: app-tag

    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith
      tags: deploy-tag
      notify: reload puma

    - name: Bundell Install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit
      tags: deploy-tag


  handlers:
    - name: restart mongod
      become: true
      systemd:
        state: restarted
        daemon_reload: yes
        name: mongod
        enabled: yes

    - name: restart puma
      become: true
      systemd:
        state: restarted
        daemon_reload: yes
        name: puma
        enabled: yes
